name: cmake_std

on:
  push:
    branches: [  ]
  pull_request:
    branches: [  ]

jobs:
  build:
    strategy:
      matrix:
        BUILD_TYPE: [Debug, Release]
        compiler: [ 
            {os: windows-latest, cpp: msvc, c: msvc, cppstd: 14 }, 
            {os: macos-latest, cpp: clang++, c: clang, cppstd: 14} ,
            {os: ubuntu-24.04, cpp: clang++-19, c: clang-19, cppstd: 14},
            {os: ubuntu-24.04, cpp: g++, c: gcc, cppstd: 14},
            {os: windows-latest, cpp: msvc, c: msvc, cppstd: 23 }, 
            {os: macos-latest, cpp: clang++, c: clang, cppstd: 23} ,
            {os: ubuntu-24.04, cpp: clang++-19, c: clang-19, cppstd: 20},
            {os: ubuntu-24.04, cpp: g++, c: gcc, cppstd: 23} 
        ]
        
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ${{ matrix.compiler.os }}

    steps:
    - uses: actions/checkout@v3
    
    - name: Install clang
      if: ${{ startsWith(matrix.compiler.os, 'ubuntu') && startsWith(matrix.compiler.cpp, 'clang') }}
      run: |
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 19 all
          rm llvm.sh

    - name: Configure CMake
      # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
      # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
      run: cmake -B ${{github.workspace}}/build -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON -DCMAKE_BUILD_TYPE=${{matrix.BUILD_TYPE}} -DCMAKE_CXX_STANDARD=${{matrix.compiler.cppstd}} -D CMAKE_C_COMPILER=${{matrix.compiler.c}} -D CMAKE_CXX_COMPILER=${{matrix.compiler.cpp}}

    - name: Build
      # Build your program with the given configuration
      run: cmake --build ${{github.workspace}}/build --config ${{matrix.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      # Execute tests defined by the CMake configuration.
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      run: ctest --verbose -C ${{matrix.BUILD_TYPE}}

