name: cmake_eastl

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    strategy:
      matrix:
        BUILD_TYPE: [Debug, Release]
        cppstd: [14, 20, 23]
        compiler: [ 
            {os: windows-latest, cpp: msvc, c: msvc }, 
            {os: macos-latest, cpp: clang++, c: clang} ,
            {os: ubuntu-20.04, cpp: clang++, c: clang},
            {os: ubuntu-20.04, cpp: g++, c: gcc}
        ]
        
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ${{ matrix.compiler.os }}

    steps:
    - uses: actions/checkout@v3
    - uses: actions/checkout@v3
      with:
        repository: electronicarts/EASTL
        path: eastl
        submodules: true
    - name: Configure CMake EASTL
      working-directory: ${{github.workspace}}/eastl
      run: cmake -B ${{github.workspace}}/eastl/build -DCMAKE_BUILD_TYPE=${{matrix.BUILD_TYPE}} -DCMAKE_CXX_STANDARD=${{matrix.cppstd}} -D CMAKE_C_COMPILER=${{matrix.compiler.c}} -D CMAKE_CXX_COMPILER=${{matrix.compiler.cpp}}

    - name: Build EASTL
      working-directory: ${{github.workspace}}/eastl
      # Build your program with the given configuration
      run: cmake --build ${{github.workspace}}/eastl/build --config ${{matrix.BUILD_TYPE}}
    
    - name: Configure CMake RAH2
      working-directory: ${{github.workspace}}
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{matrix.BUILD_TYPE}} -DCMAKE_CXX_STANDARD=${{matrix.cppstd}} -D CMAKE_C_COMPILER=${{matrix.compiler.c}} -D CMAKE_CXX_COMPILER=${{matrix.compiler.cpp}} -D RAH2_INSIDE_EASTL=1 -DEASTL_DIR="${{github.workspace}}/eastl"

    - name: Build RAH2
      working-directory: ${{github.workspace}}
      # Build your program with the given configuration
      run: cmake --build ${{github.workspace}}/build --config ${{matrix.BUILD_TYPE}}

    - name: Test RAH2
      working-directory: ${{github.workspace}}/build
      # Execute tests defined by the CMake configuration.
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      run: ctest --verbose -C ${{matrix.BUILD_TYPE}}

