name: clang_format

on:
  pull_request:
    branches: [ "master" ]
    
jobs:
  clang_format:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.ref }}

    - name: Setup clang
      run: |
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 18 all
          rm llvm.sh
    
    - name: Get clang version
      run: clang-format-18 --version 

    - name: Format All
      run: find . -regex '.*\.\(cpp\|hpp\|cc\|cxx\|c\)' -exec clang-format-18 --verbose -style=file -i {} \;

    - name: Amend the last commit
      run: |
          git config --global user.email "loic.hamot@yahoo.fr"
          git config --global user.name "lhamot"
          git commit -a -m "formating"
          git push
          echo "Complete"