name: clang_format

on:
  pull_request:
    branches: [ "master" ]
    
jobs:
  clang_format:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.ref }}

    - name: Setup clang
      run: |
          deb http://apt.llvm.org/focal/ llvm-toolchain-focal-18 main
          deb-src http://apt.llvm.org/focal/ llvm-toolchain-focal-18 main
          apt-get install clang-format-18
    
    - name: Get clang version
      run: clang-format --version 

    - name: Format All
      run: find . -regex '.*\.\(cpp\|hpp\|cc\|cxx\|c\)' -exec clang-format --verbose -style=file -i {} \;

    - name: Amend the last commit
      run: |
          git config --global user.email "loic.hamot@yahoo.fr"
          git config --global user.name "lhamot"
          git commit -a -m "formating"
          git push
          echo "Complete"